---
title: "Analysis eGeMAPS"
author: "Marie Mortensen"
date: "10/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

PACKAGES AND FUNCTIONS
```{r}
pacman::p_load(tidyverse, readr, glmnet, data.table, broom, forcats, e1071, cvms)
source("functions/Inspection.R")
source("functions/Normalize_function.R")
#source("functions/cv funtions .R")
source("functions/Lasso loop function.R")
source("functions/clean column function.R")
```

Loading data 
```{r}
compare_dk <- read_csv("compare_dk.csv")
compare_us <- read_csv("compare_us.csv")
egemaps_dk <- read_csv("egemaps_dk.csv")
egemaps_us <- read_csv("egemaps_us.csv")
gemaps_dk  <- read_csv("gemaps_dk.csv") 
gemaps_us  <- read_csv("gemaps_us.csv")
demodata   <- read_csv("DemoData.csv")

```

Function to run on all six files
```{r}
grand_function <- function(feature_dataframe, demo_dataframe, language, featureset, n_lasso_folds = 5){
  ###Getting the correct dataframes###
  features <- feature_dataframe %>% select(-name)
  demo <- demo_dataframe %>% filter(language == language)
  
  ###Cleaning the data###
  features <- features %>% 
  mutate(
   ID = as.character(ID),  #Making ID character
    ID_letter = str_extract(ID, "[A-Z]*"), #extracting letters from ID name
    ID_number = str_extract(ID, "[0-9]*")  #extracting numbers from ID name
  )

  features <- features %>% 
    unite(ID, ID_letter:ID_number, sep = "") 
  
  ###removing missing ID from demodata for danish datasets###
  if (language == "dk"){
  demo <- demo %>% subset(ID != "103"& ID != "104"& ID !="105"& ID !="111"& ID !="114")
  }
  
  ###partitioning###
  partitions <- partition_func(features = features, 
                               demo = demo, 
                               n = uniqueN(features$ID),
                               language = language) 
  train <- partitions[[2]]
  hold_out <- partitions[[1]]

  #normalizing - scale_function takes min and max of all columns in train and subtracts min from all   values in each columns and divides by max value to get the empirically scaled columns
  train_scaled <- as.data.frame(
    scale_function(train, datatype = "train"))

  hold_out_scaled <- as.data.frame(
  scale_function(train, 
                 hold_out, 
                 datatype = "test"))
  
  ###Combining demo and feature-set values###
  train_scaled <- train_scaled %>% #combining demodata and features
  left_join(demo, 
            by = "ID") %>% 
  mutate(
    Diagnosis = as.factor(Diagnosis) #changing diagnosis column to factor
  )  %>% 
  select( #we will not use any of the descriptive columns in the analysis and remove them from the dataset 
  -c(X1,
    condition,
    frameTime, 
    language, 
    country, 
    feature_set, 
    story_type,
    Age,
    AdosCreativity,
    AdosSocial,
    AdosStereotyped,
    AdosCommunication,
    TIQ,
    PIQ,
    VIQ,
    SRS,
    PPVT,
    ParentalEducation,
    CARS,
    Leiter
     ))
  
  ###Removing column w/ zero variation and no factor variation###
  badcolumns <- clean_cols(df = train_scaled)
  train_scaled_clean <- train_scaled[ ,!(colnames(train_scaled) %in% c(badcolumns))] 
  
  ###Lasso looping ###
  lasso_function(train_data = train_scaled_clean, 
                 folds = n_lasso_folds,
                 id_col = "ID", 
                 featureset = featureset, 
                 language = language)
  
}
```

Running on gemaps_dk
```{r}
grand_function(feature_dataframe = gemaps_dk, 
               demo_dataframe = demodata, 
               language = "dk",
               featureset = "gemaps")
```

Running on gemaps_us
```{r}
grand_function(feature_dataframe = gemaps_us, 
               demo_dataframe = demodata, 
               language = "us",
               featureset = "gemaps")
```

Running on egemaps_dk
```{r}

```


What does it look like?
```{r}
# test_1 <- read_csv("lasso_gemaps_dk_testfold_1.csv")
# test_2 <- read_csv("lasso_gemaps_dk_testfold_2.csv")
# test_3 <- read_csv("lasso_gemaps_dk_testfold_3.csv")
# test_4 <- read_csv("lasso_gemaps_dk_testfold_4.csv")
# test_5 <- read_csv("lasso_gemaps_dk_testfold_5.csv")
```

