---
title: "Untitled"
author: "Marie Mortensen"
date: "9/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(stringr, readr, tidyverse)
options(scipen = 1000)

#all compare
output_all_features <- read_delim(
  "../wav_files/output_files/us_stories_7352.04_elephants_comp_all.csv",
  ";",
  escape_double = FALSE,
  col_names = T
)


#gemap
test_dk_gemap <-
  read_delim(
    "../wav_files/gemaps/dk_stories_101A_1_gemap_all.csv",
    ";",
    escape_double = FALSE,
    col_names = T,
    trim_ws = TRUE
  )

issue_file <- 
  read_delim(
    "../wav_files/output_files/us_stories_0919_lemurs_gemap_all.csv",
    ";",
    escape_double = FALSE,
    col_names = T,
    trim_ws = TRUE
  )

```

looping through files
```{r}
input_list <- list.files("../wav_files/input_files/", pattern = ".wav")
length(input_list)
options(max.print = 2000)

files_list <- list.files("../wav_files/gemaps/", pattern = ".csv")
length(files_list)

for (i in 1:length(files_list)){
  print(i)
file <- read_delim(
  paste("../wav_files/gemaps/",files_list[i], sep = "/"),
  ";",
  escape_double = FALSE,
  trim_ws = TRUE
)
file$name <-NA
file$story_type = NA
file$condition = NA
file$trial = NA
file$country <- str_extract(files_list[i],"^[a-z]{2}")

if(file$country == "dk"){
info_list <- stringr::str_match(files_list[i], ".{2}_([a-z]*)_([0-9A-Z]*)[._]([0-9]*)[_]*([a-z]*)_([a-z]*[_]?[a-z]*)")
file$story_type <- NA
file$name <- info_list[,3]
file$condition <- info_list[,2]
file$trial <- info_list[,4]
file$feature_set <- info_list[,5]
}

if(file$country == "us"){ #for US stories you have: us_stories_1956_elephants, us is the language, stories the task, 1956 the ID, elephants the story name
info_list <-stringr::str_match(files_list[i],
 ".{2}_([a-z]*)_([0-9A-Z]*)[._]([0-9]*)[_ ]*([a-z]*)_([a-z]*[_]?[a-z]*)")              

file$story_type <- info_list[,5]
file$name <- info_list[,3]
file$condition <- info_list[,2]
file$trial <- info_list[,4]
file$feature_set <- info_list[,6]
}
if(i == 1){
  all_files <- file
  }
else{
    all_files <- rbind(all_files, file)
  }
}

write.csv(all_files, "gemap_all_us_dk_v2.csv")
getwd()
head(all_files)
```

Adding demodata
```{r}
demo <- read_csv("../DemoData.csv")
unique(all_files$ID)
colnames(all_files)[1] <- "ID_original"
all_files <- all_files %>% mutate(
  ID = str_extract(ID_original, "[0-9]*")
) 

gemap_all <- left_join(all_files, demo, by = "ID")
gemap_all <- gemap_all %>% mutate(
  Diag_Case = ifelse(Diagnosis=="ASD", 1, 0)
) 

```



